### ISSUE TITLE
lab error in argocd WebUI and not responding lab terminal .

### ISSUE THREAD

**Issue by erramre** [mabusaa/argocd-course-issues-tracker#11]
lab error in argocd WebUI
InvalidSpecError:
cluster 'https://kubernetes.default.svc ' has not been configured 
AND also while setting port number to 443 it is not working.

controlplane $ kubectl port-forward svc/argocd-server -n argocd 8080:443
Forwarding from 127.0.0.1:8080 -> 8080
Forwarding from [::1]:8080 -> 8080
only these 2 lines are the output and session hanged.

**Comment by mabusaa** [comment]
hi, can you please post the lab url ?

**Comment by erramre** [comment]
https://killercoda.com/mabusaa/course/argocd-endusers-scenarios/02-argocd-cli

**Comment by erramre** [comment]
InvalidSpecError:
cluster 'https://kubernetes.default.svc/ ' has not been configured
AND also while setting port number to 443 it is not working.
The above url  is not working in any lab. (i.e) Iam getting same error in every lab.

**Comment by mabusaa** [comment]
the lab is working perfectly as per the lab instructions  , in the lab you mentioned, nothing mentioned to use port forward.
in almost all labs we are using service of type nodeport to expose argo ui 
![image](https://user-images.githubusercontent.com/13915373/200118323-f4c35ee0-69c3-415e-9dad-df389498e6c8.png)

in all labs instructions there is a link to use to open argo cd web , example:

![image](https://user-images.githubusercontent.com/13915373/200118369-4ec34aed-f97e-422e-8a2f-7829c762dabe.png)

**Comment by mabusaa** [comment]
port forward is one way to access argocd server, and usually we use it in our machines (laptops).
other ways such as using service of type nodeport or load balancer or ingress can be used also.
in these labs , we are using service of type nodeport, so no need to use port forward

**Comment by mabusaa** [comment]
please try to follow the labs instructions and let me know if there anything not clear or not working
