### ISSUE TITLE
namespace app-1 not created/needs to add step

### ISSUE THREAD

**Issue by garayevxalid** [mabusaa/argocd-course-issues-tracker#15]
Hi, Thank you for the playground. Needs to add step for creating app-1 namespace for synchronizing argocd
![image](https://user-images.githubusercontent.com/22119265/222973411-8864346a-24f7-485a-9731-babb0cf6b4b6.png)

**Comment by mabusaa** [comment]
Hi,

that was intentional , the practice is telling you to use auto create namespace in application sync options :)

**Comment by garayevxalid** [comment]
Thank you for your response. got point. Seems I forgot to tick a checkbox
for autocreating namespce.
Regards,
Khalid G.
