### ISSUE TITLE
Base64 Decode command not working.

### ISSUE THREAD

**Issue by SubinayNag** [mabusaa/argocd-course-issues-tracker#17]
[Text.Encoding]::Utf8.GetString([Convert]::FromBase64String('******'))
bash: syntax error near unexpected token `[Convert]::FromBase64String'

**Comment by mabusaa** [comment]
can you share in which lab you are experiencing this , and the exact command you are using ?

**Comment by SubinayNag** [comment]
The problem is solved now.

[Text.Encoding]::Utf8.GetString([Convert]::FromBase64String('***'))

This is the command that I was using to decode. It was not working in CMD but worked in powershell.
