### ISSUE TITLE
2nd repository mambusaa/argocd-course-webapp-config not mentioned and authorization is failing

### ISSUE THREAD

**Issue by tomas-st** [mabusaa/argocd-course-issues-tracker#18]
In 

- Lecture 111 Dynamic Environments Using Pull Request Generator 

there is no hint to fork mambusaa/argocd-course-webapp-config (CONFIG_REPO_NAME) in addition to mambusaa/argocd-course-webapp. 

But this repository is used in  .github/workflows/ci.yaml. And it is not mentioned to change the tag name in ci.yaml as well. So I suppose I am expected to use your argocd-course-webapp-config. But I do not have permissions to push the new tag value to helm/webapp/values.yaml in this repository.

Am I expected to fork this repository as well for this lecture and set all necessary github secrets on this repository?  

If I use the same repository <my-git-username>/argocd-course-webapp in ci-yaml the build pipeline will start over and over because of the pushed tag value in helm/webapp/values.yaml.

Error is: Error: buildx failed with: ERROR: failed to solve: failed to push mabusaa/argocd-course-webapp:2e7947fced461576f60057e0d9932b0632ee9dfb: server message: insufficient_scope: authorization failed

**Comment by mabusaa** [comment]
Hi,

Thank you for opening this discussion,

In Lab step2, the first point mentioned is to use Forked repo,

```

- Use your forked webapp repo.
- Application-set name: webapp-review
- Generate applications for open pull requests that has label of preview .
- Generated application name: should include source branch name and pull request number.
.... 
etc
```

**Comment by mabusaa** [comment]
in all labs , users should use their Forked repos especially labs that instruct users to do write/push into repo code.

**Comment by tomas-st** [comment]
Thank you for your fast reply. It's correct that it is mentioned in the second step to "fork the webapp repo https://github.com/mabusaa/argocd-course-webapp" and I understand that the solution ist to fork both repositories.

Perhaps it could be useful for future practitioners to mention the second config repository, too. This is not mentioned anywhere. As well as the need to replace variables in ci.yaml and setting github secrets in the second repository "argocd-course-webapp-config", too. As in the third step only those two files are mentioned and not ci.yaml:
In pr yaml file: https://github.com/mabusaa/argocd-course-webapp/blob/main/.github/workflows/pr.yml#L39
In helm chart values file: https://github.com/mabusaa/argocd-course-webapp/blob/main/helm/webapp/values.yaml#L8

**Comment by mabusaa** [comment]
In PR generator lab , config repo is not used, the helm values update will happen in the source branch. https://github.com/mabusaa/argocd-course-webapp/blob/main/.github/workflows/pr.yml#L50 
so forking only the webapp repo is enough. 

I guess you are telling about another lab and lecture in which we are using config repo. I will verify if I am missing the hints to fork both repos.

**Comment by tomas-st** [comment]
Thanks a lot for your ongoing effort. The issue is solved now. I was confused by the running (and failing) CI pipeline after pushing to the forked repo and assumed it must succeed for this lecture. But of course - as you said - it is not part of this lecture. So everything works for me now.
