### ISSUE TITLE
How to connect argocd to eks cluster using IAM ole

### ISSUE THREAD

**Issue by devindersuri** [mabusaa/argocd-course-issues-tracker#19]
I have 2 clusters, one runnign argocd and aother running application.
I used token to add eks cluster to argocd but i believe that token expires itself after some time. 
I know that we can provide iam role to connect but dont know how.

**Comment by mabusaa** [comment]
Hello,

Pls check this blog post , it describe how to do it in aws using role 

https://www.modulo2.nl/blog/argocd-on-aws-with-multiple-clusters
