### ISSUE TITLE
Cannot change repository visibility 

### ISSUE THREAD

**Issue by zs856** [mabusaa/argocd-course-issues-tracker#2]
I fork the repo but I cannot make it private.  [Please check this](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/managing-repository-settings/setting-repository-visibility#about-repository-visibility-changes)

**Comment by mabusaa** [comment]
Ohh, you are correct , possible workaround :

1. Create an empty repo (private)
2. Click Import code
3. Paste my repo url

**Comment by mabusaa** [comment]
practice updated with this workaround , thank you for reporting this

**Comment by zs856** [comment]
great. I have passed practices for private repo! Thx
