### ISSUE TITLE
ArgoCD server hanging with CrashLoopBackOff status post deplyment

### ISSUE THREAD

**Issue by tee-lake** [mabusaa/argocd-course-issues-tracker#20]
Not all pods get to running state

controlplane $ kubectl get pods -n argocd
NAME                                                READY   STATUS             RESTARTS      AGE
argocd-application-controller-0                     0/1     Running            0             3m5s
argocd-applicationset-controller-57db5f5c7d-8pjzn   1/1     Running            1 (51s ago)   3m5s
argocd-dex-server-c4b8545d-fhgkj                    1/1     Running            0             3m5s
argocd-notifications-controller-7cddc64d84-vsfxf    1/1     Running            0             3m5s
argocd-redis-6b7c6f67db-cw6br                       1/1     Running            0             3m5s
argocd-repo-server-6867ddcc74-h45g8                 1/1     Running            0             3m5s
argocd-server-64957744c9-cp9t8                      0/1     **CrashLoopBackOff**   4 (81s ago)   3m5s

**Comment by mabusaa** [comment]
Hello,

In which lab is this happening ? or is it in your local machine ?
