### ISSUE TITLE
Update /practice/application.yaml destination name field to destination server in Basic CICD practice lab.

### ISSUE THREAD

**Issue by tomngu2** [mabusaa/argocd-course-issues-tracker#24]
Was working on Basic CICD practice lab and was wondering why I couldn't get the app to sync.  After updating initial /practice/application.yaml destination name to destination server, was able to sync.  Please update the initial /practice/application.yaml from name to server.

![Basic CICD screenshot](https://github.com/mabusaa/argocd-course-issues-tracker/assets/52871921/31512757-782a-486f-889a-dcf35d08a343)

Regards,
Tom

**Comment by mabusaa** [comment]
Thanks for reporting , this is fixed
