### ISSUE TITLE
When should I use "Applicatonset" and app of apps

### ISSUE THREAD

**Issue by zs856** [mabusaa/argocd-course-issues-tracker#5]
"Applicatonset" and app of apps can be used to manage multiple apps. Therefore, I wonder what is the best practice to combine these two methods. Is there any suggestion for this?

**Comment by mabusaa** [comment]
Both can manage/deploy multiple apps , ApplicationSet has more flexibility with the power of generators , (read more about generators).
ApplicationSet considered an evolution of App of Apps pattern with lots of features.

You can combine it in many options, such using a app of apps that deploy a normal apps and application sets , example: 
- root app (app of apps)
   - normal app1
   - normal app2
   - application set (deploys apps into multi clusters)
      - app1-cluster1
      - app1-cluster2
      - app2-cluster1
      - app2-cluster2
      ....

**Comment by zs856** [comment]
> Both can manage/deploy multiple apps , ApplicationSet has more flexibility with the power of generators , (read more about generators). ApplicationSet considered an evolution of App of Apps pattern with lots of features.
> 
> You can combine it in many options, such using a app of apps that deploy a normal apps and application sets , example:
> 
> * root app (app of apps)
>   
>   * normal app1
>   * normal app2
>   * application set (deploys apps into multi clusters)
>     
>     * app1-cluster1
>     * app1-cluster2
>     * app2-cluster1
>     * app2-cluster2
>       ....

It has been really helpful. Thank you.
