### ISSUE TITLE
How to improve ArgoCD's performance

### ISSUE THREAD

**Issue by zs856** [mabusaa/argocd-course-issues-tracker#6]
<img width="535" alt="image" src="https://user-images.githubusercontent.com/42588942/190351391-77ba611d-b863-4dc0-ac4e-a705995dd743.png">
Hi,  I installed a HA ArgoCD on the AWS EKS and I deployed several applications on ArgoCD. The ArgoCD is managing applications on different clusters. Sometimes, when I click on an application, it will give me the feedback as above. I wonder what can I do to avoid this. Is it a problem with EKS network bandwidth?

**Comment by mabusaa** [comment]
how many apps you mean by several , argo cd can handle hundreds without an issue unless you work on only monorepo , then it can cause slowness, can you share more details

**Comment by zs856** [comment]
> how many apps you mean by several , argo cd can handle hundreds without an issue unless you work on only monorepo , then it can cause slowness, can you share more details

OK. Assuming I have run ArgoCD already, here below is the step I took :
- 1. creating a config repo in [gitee](https://gitee.com/)
- 2. creating a folder with 3 applications in the repo
- 3. creating three folders with "deployment.yaml" in the repo. Each folder is related to an application. 
- 4. I use a root app to manage other apps. I run "kubectl apply -f root-app-directory-approach.yaml" in this step
- 5. ArgoCD shows up 4 applications including root app

**Comment by mabusaa** [comment]
that will not cause any performance issue as its only small number of apps, I think you are having network issues as the error stated.

**Comment by zs856** [comment]
> 

I see. lol. What a strange network. Sometimes, I have to refresh the page two times to get data on the page. Sometimes, Argo can get data fluently without requiring to refresh. Are there any methods I can use to spot the network bottleneck?

**Comment by mabusaa** [comment]
question are you using argo cd behind a reverse proxy ?

**Comment by zs856** [comment]
> 

I think the answer is no. I just follow the [argo tutorial](https://argo-cd.readthedocs.io/en/stable/operator-manual/ingress/#aws-application-load-balancers-albs-and-classic-elb-http-mode) here. I configured an alb. Oh, my cluster is a three-node (t3.small) cluster,  will this be a problem?

**Comment by mabusaa** [comment]
so you create another service as per the docs and configured an ingress resource ? are there any other workloads running on the cluster ? such as service meshes ?

**Comment by zs856** [comment]
> so you create another service as per the docs and configured an ingress resource ? are there any other workloads running on the cluster ? such as service meshes ?

1. Yes
2. NO, only ArgoCD v2.4.11
3. NO

**Comment by mabusaa** [comment]
maybe the nodes resources can lead to this, can u check if pods are distributed into multiple nodes 
`kubectl get po -n argocd -o wide`

**Comment by zs856** [comment]
<img width="516" alt="企业微信截图_16633335134374" src="https://user-images.githubusercontent.com/42588942/190645506-6ef110b6-271b-4223-984e-d33ddad67227.png">
yes. It seems that these resources are distributed in three nodes.
I also noticed there is a restart occurring in a proxy, the file below includes the detail of it:

[rgocd-redis-ha-haproxy.txt](https://github.com/mabusaa/argocd-course-issues-tracker/files/9584367/rgocd-redis-ha-haproxy.txt)

**Comment by mabusaa** [comment]
can you please try a different shape with higher resources , at least 2 cpu and 4 gb ram, you can start with two nodes only at first , and start with Non-HA setup .

**Comment by zs856** [comment]
not sure about the reason. While it seems HA deployment works fine now by adding more nodes into the cluster.

**Comment by mabusaa** [comment]
adding more nodes or increasing resources will solve the issue since you were using small nodes shape
