### ISSUE TITLE
The start time for the ArgoCD pods is too large

### ISSUE THREAD

**Issue by jjuarez** [mabusaa/argocd-course-issues-tracker#8]
After several attempts and waiting for minutes, the scenario was not able to check the exercise results because the pods were not ready.

<img width="1309" alt="Screenshot 2022-09-20 at 11 17 56" src="https://user-images.githubusercontent.com/47994/191219603-99d9ec07-c693-4cb2-9abc-cd6a51bbff58.png">

Taking a look at the cluster events, I've seen that 

<img width="1328" alt="Screenshot 2022-09-20 at 11 19 26" src="https://user-images.githubusercontent.com/47994/191220008-8f414eb6-5dd7-4a9f-bf28-6cb078169cb9.png">

**Comment by mabusaa** [comment]
can you please mention which scenario is this , can u share the url ?

**Comment by mabusaa** [comment]
seems there was an issue with infra/platform , i tried random scenario 
![image](https://user-images.githubusercontent.com/13915373/191224712-0c255e9a-44b7-4f62-8e18-71627ca55398.png)

**Comment by jjuarez** [comment]
This is the scenario URL: https://killercoda.com/mabusaa/course/argocd-endusers-scenarios/01-setting-up-argocd and yes, this seems like a platform issue

**Comment by mabusaa** [comment]
seems i have to use two nodes environment, because i experience the same on the same scenario, will update it to be 2 nodes cluster

**Comment by mabusaa** [comment]
updated the scenario to run on top of 2 nodes cluster, should be much better now. pods will be distributed on two nodes .

**Comment by jjuarez** [comment]
Thank you, no it's working perfectly!
