### ISSUE TITLE
can you please let me know the process of installing the argocd using the Helm charts

### ISSUE THREAD

**Issue by naresh0516** [mabusaa/argocd-course-issues-tracker#9]

**Comment by mabusaa** [comment]
run below commands:

1. helm repo add argo https://argoproj.github.io/argo-helm
2. kubectl create ns argocd 
3. helm install my-release argo/argo-cd -n argocd

4. verify the pods are ready 
kubectl get pods -n argocd 

source:  https://github.com/argoproj/argo-helm/tree/main/charts/argo-cd

**Comment by naresh0516** [comment]
thank you. Will try
